QT += quick
CONFIG += c++11

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        main.cpp \
    adc.cpp \
    radio.cpp \
    backendinterface.cpp \
    stream.cpp \
    serial.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

INCLUDEPATH += /usr/local/lib
LIBS += -L"/usr/local/lib" -lpigpio

HEADERS += \
    adc.h \
    radio.h \
    backendinterface.h \
    mavlink/common/common.h \
    mavlink/common/common.hpp \
    mavlink/common/gtestsuite.hpp \
    mavlink/common/mavlink.h \
    mavlink/common/mavlink_msg_actuator_control_target.h \
    mavlink/common/mavlink_msg_actuator_control_target.hpp \
    mavlink/common/mavlink_msg_adsb_vehicle.h \
    mavlink/common/mavlink_msg_adsb_vehicle.hpp \
    mavlink/common/mavlink_msg_altitude.h \
    mavlink/common/mavlink_msg_altitude.hpp \
    mavlink/common/mavlink_msg_att_pos_mocap.h \
    mavlink/common/mavlink_msg_att_pos_mocap.hpp \
    mavlink/common/mavlink_msg_attitude.h \
    mavlink/common/mavlink_msg_attitude.hpp \
    mavlink/common/mavlink_msg_attitude_quaternion.h \
    mavlink/common/mavlink_msg_attitude_quaternion.hpp \
    mavlink/common/mavlink_msg_attitude_quaternion_cov.h \
    mavlink/common/mavlink_msg_attitude_quaternion_cov.hpp \
    mavlink/common/mavlink_msg_attitude_target.h \
    mavlink/common/mavlink_msg_attitude_target.hpp \
    mavlink/common/mavlink_msg_auth_key.h \
    mavlink/common/mavlink_msg_auth_key.hpp \
    mavlink/common/mavlink_msg_autopilot_version.h \
    mavlink/common/mavlink_msg_autopilot_version.hpp \
    mavlink/common/mavlink_msg_battery_status.h \
    mavlink/common/mavlink_msg_battery_status.hpp \
    mavlink/common/mavlink_msg_button_change.h \
    mavlink/common/mavlink_msg_button_change.hpp \
    mavlink/common/mavlink_msg_camera_capture_status.h \
    mavlink/common/mavlink_msg_camera_capture_status.hpp \
    mavlink/common/mavlink_msg_camera_image_captured.h \
    mavlink/common/mavlink_msg_camera_image_captured.hpp \
    mavlink/common/mavlink_msg_camera_information.h \
    mavlink/common/mavlink_msg_camera_information.hpp \
    mavlink/common/mavlink_msg_camera_settings.h \
    mavlink/common/mavlink_msg_camera_settings.hpp \
    mavlink/common/mavlink_msg_camera_trigger.h \
    mavlink/common/mavlink_msg_camera_trigger.hpp \
    mavlink/common/mavlink_msg_change_operator_control.h \
    mavlink/common/mavlink_msg_change_operator_control.hpp \
    mavlink/common/mavlink_msg_change_operator_control_ack.h \
    mavlink/common/mavlink_msg_change_operator_control_ack.hpp \
    mavlink/common/mavlink_msg_collision.h \
    mavlink/common/mavlink_msg_collision.hpp \
    mavlink/common/mavlink_msg_command_ack.h \
    mavlink/common/mavlink_msg_command_ack.hpp \
    mavlink/common/mavlink_msg_command_int.h \
    mavlink/common/mavlink_msg_command_int.hpp \
    mavlink/common/mavlink_msg_command_long.h \
    mavlink/common/mavlink_msg_command_long.hpp \
    mavlink/common/mavlink_msg_control_system_state.h \
    mavlink/common/mavlink_msg_control_system_state.hpp \
    mavlink/common/mavlink_msg_data_stream.h \
    mavlink/common/mavlink_msg_data_stream.hpp \
    mavlink/common/mavlink_msg_data_transmission_handshake.h \
    mavlink/common/mavlink_msg_data_transmission_handshake.hpp \
    mavlink/common/mavlink_msg_debug.h \
    mavlink/common/mavlink_msg_debug.hpp \
    mavlink/common/mavlink_msg_debug_vect.h \
    mavlink/common/mavlink_msg_debug_vect.hpp \
    mavlink/common/mavlink_msg_distance_sensor.h \
    mavlink/common/mavlink_msg_distance_sensor.hpp \
    mavlink/common/mavlink_msg_encapsulated_data.h \
    mavlink/common/mavlink_msg_encapsulated_data.hpp \
    mavlink/common/mavlink_msg_estimator_status.h \
    mavlink/common/mavlink_msg_estimator_status.hpp \
    mavlink/common/mavlink_msg_extended_sys_state.h \
    mavlink/common/mavlink_msg_extended_sys_state.hpp \
    mavlink/common/mavlink_msg_file_transfer_protocol.h \
    mavlink/common/mavlink_msg_file_transfer_protocol.hpp \
    mavlink/common/mavlink_msg_flight_information.h \
    mavlink/common/mavlink_msg_flight_information.hpp \
    mavlink/common/mavlink_msg_follow_target.h \
    mavlink/common/mavlink_msg_follow_target.hpp \
    mavlink/common/mavlink_msg_global_position_int.h \
    mavlink/common/mavlink_msg_global_position_int.hpp \
    mavlink/common/mavlink_msg_global_position_int_cov.h \
    mavlink/common/mavlink_msg_global_position_int_cov.hpp \
    mavlink/common/mavlink_msg_global_vision_position_estimate.h \
    mavlink/common/mavlink_msg_global_vision_position_estimate.hpp \
    mavlink/common/mavlink_msg_gps2_raw.h \
    mavlink/common/mavlink_msg_gps2_raw.hpp \
    mavlink/common/mavlink_msg_gps2_rtk.h \
    mavlink/common/mavlink_msg_gps2_rtk.hpp \
    mavlink/common/mavlink_msg_gps_global_origin.h \
    mavlink/common/mavlink_msg_gps_global_origin.hpp \
    mavlink/common/mavlink_msg_gps_inject_data.h \
    mavlink/common/mavlink_msg_gps_inject_data.hpp \
    mavlink/common/mavlink_msg_gps_input.h \
    mavlink/common/mavlink_msg_gps_input.hpp \
    mavlink/common/mavlink_msg_gps_raw_int.h \
    mavlink/common/mavlink_msg_gps_raw_int.hpp \
    mavlink/common/mavlink_msg_gps_rtcm_data.h \
    mavlink/common/mavlink_msg_gps_rtcm_data.hpp \
    mavlink/common/mavlink_msg_gps_rtk.h \
    mavlink/common/mavlink_msg_gps_rtk.hpp \
    mavlink/common/mavlink_msg_gps_status.h \
    mavlink/common/mavlink_msg_gps_status.hpp \
    mavlink/common/mavlink_msg_heartbeat.h \
    mavlink/common/mavlink_msg_heartbeat.hpp \
    mavlink/common/mavlink_msg_high_latency.h \
    mavlink/common/mavlink_msg_high_latency.hpp \
    mavlink/common/mavlink_msg_high_latency2.h \
    mavlink/common/mavlink_msg_high_latency2.hpp \
    mavlink/common/mavlink_msg_highres_imu.h \
    mavlink/common/mavlink_msg_highres_imu.hpp \
    mavlink/common/mavlink_msg_hil_actuator_controls.h \
    mavlink/common/mavlink_msg_hil_actuator_controls.hpp \
    mavlink/common/mavlink_msg_hil_controls.h \
    mavlink/common/mavlink_msg_hil_controls.hpp \
    mavlink/common/mavlink_msg_hil_gps.h \
    mavlink/common/mavlink_msg_hil_gps.hpp \
    mavlink/common/mavlink_msg_hil_optical_flow.h \
    mavlink/common/mavlink_msg_hil_optical_flow.hpp \
    mavlink/common/mavlink_msg_hil_rc_inputs_raw.h \
    mavlink/common/mavlink_msg_hil_rc_inputs_raw.hpp \
    mavlink/common/mavlink_msg_hil_sensor.h \
    mavlink/common/mavlink_msg_hil_sensor.hpp \
    mavlink/common/mavlink_msg_hil_state.h \
    mavlink/common/mavlink_msg_hil_state.hpp \
    mavlink/common/mavlink_msg_hil_state_quaternion.h \
    mavlink/common/mavlink_msg_hil_state_quaternion.hpp \
    mavlink/common/mavlink_msg_home_position.h \
    mavlink/common/mavlink_msg_home_position.hpp \
    mavlink/common/mavlink_msg_landing_target.h \
    mavlink/common/mavlink_msg_landing_target.hpp \
    mavlink/common/mavlink_msg_local_position_ned.h \
    mavlink/common/mavlink_msg_local_position_ned.hpp \
    mavlink/common/mavlink_msg_local_position_ned_cov.h \
    mavlink/common/mavlink_msg_local_position_ned_cov.hpp \
    mavlink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    mavlink/common/mavlink_msg_local_position_ned_system_global_offset.hpp \
    mavlink/common/mavlink_msg_log_data.h \
    mavlink/common/mavlink_msg_log_data.hpp \
    mavlink/common/mavlink_msg_log_entry.h \
    mavlink/common/mavlink_msg_log_entry.hpp \
    mavlink/common/mavlink_msg_log_erase.h \
    mavlink/common/mavlink_msg_log_erase.hpp \
    mavlink/common/mavlink_msg_log_request_data.h \
    mavlink/common/mavlink_msg_log_request_data.hpp \
    mavlink/common/mavlink_msg_log_request_end.h \
    mavlink/common/mavlink_msg_log_request_end.hpp \
    mavlink/common/mavlink_msg_log_request_list.h \
    mavlink/common/mavlink_msg_log_request_list.hpp \
    mavlink/common/mavlink_msg_logging_ack.h \
    mavlink/common/mavlink_msg_logging_ack.hpp \
    mavlink/common/mavlink_msg_logging_data.h \
    mavlink/common/mavlink_msg_logging_data.hpp \
    mavlink/common/mavlink_msg_logging_data_acked.h \
    mavlink/common/mavlink_msg_logging_data_acked.hpp \
    mavlink/common/mavlink_msg_manual_control.h \
    mavlink/common/mavlink_msg_manual_control.hpp \
    mavlink/common/mavlink_msg_manual_setpoint.h \
    mavlink/common/mavlink_msg_manual_setpoint.hpp \
    mavlink/common/mavlink_msg_memory_vect.h \
    mavlink/common/mavlink_msg_memory_vect.hpp \
    mavlink/common/mavlink_msg_message_interval.h \
    mavlink/common/mavlink_msg_message_interval.hpp \
    mavlink/common/mavlink_msg_mission_ack.h \
    mavlink/common/mavlink_msg_mission_ack.hpp \
    mavlink/common/mavlink_msg_mission_clear_all.h \
    mavlink/common/mavlink_msg_mission_clear_all.hpp \
    mavlink/common/mavlink_msg_mission_count.h \
    mavlink/common/mavlink_msg_mission_count.hpp \
    mavlink/common/mavlink_msg_mission_current.h \
    mavlink/common/mavlink_msg_mission_current.hpp \
    mavlink/common/mavlink_msg_mission_item.h \
    mavlink/common/mavlink_msg_mission_item.hpp \
    mavlink/common/mavlink_msg_mission_item_int.h \
    mavlink/common/mavlink_msg_mission_item_int.hpp \
    mavlink/common/mavlink_msg_mission_item_reached.h \
    mavlink/common/mavlink_msg_mission_item_reached.hpp \
    mavlink/common/mavlink_msg_mission_request.h \
    mavlink/common/mavlink_msg_mission_request.hpp \
    mavlink/common/mavlink_msg_mission_request_int.h \
    mavlink/common/mavlink_msg_mission_request_int.hpp \
    mavlink/common/mavlink_msg_mission_request_list.h \
    mavlink/common/mavlink_msg_mission_request_list.hpp \
    mavlink/common/mavlink_msg_mission_request_partial_list.h \
    mavlink/common/mavlink_msg_mission_request_partial_list.hpp \
    mavlink/common/mavlink_msg_mission_set_current.h \
    mavlink/common/mavlink_msg_mission_set_current.hpp \
    mavlink/common/mavlink_msg_mission_write_partial_list.h \
    mavlink/common/mavlink_msg_mission_write_partial_list.hpp \
    mavlink/common/mavlink_msg_mount_orientation.h \
    mavlink/common/mavlink_msg_mount_orientation.hpp \
    mavlink/common/mavlink_msg_named_value_float.h \
    mavlink/common/mavlink_msg_named_value_float.hpp \
    mavlink/common/mavlink_msg_named_value_int.h \
    mavlink/common/mavlink_msg_named_value_int.hpp \
    mavlink/common/mavlink_msg_nav_controller_output.h \
    mavlink/common/mavlink_msg_nav_controller_output.hpp \
    mavlink/common/mavlink_msg_obstacle_distance.h \
    mavlink/common/mavlink_msg_obstacle_distance.hpp \
    mavlink/common/mavlink_msg_odometry.h \
    mavlink/common/mavlink_msg_odometry.hpp \
    mavlink/common/mavlink_msg_optical_flow.h \
    mavlink/common/mavlink_msg_optical_flow.hpp \
    mavlink/common/mavlink_msg_optical_flow_rad.h \
    mavlink/common/mavlink_msg_optical_flow_rad.hpp \
    mavlink/common/mavlink_msg_param_ext_ack.h \
    mavlink/common/mavlink_msg_param_ext_ack.hpp \
    mavlink/common/mavlink_msg_param_ext_request_list.h \
    mavlink/common/mavlink_msg_param_ext_request_list.hpp \
    mavlink/common/mavlink_msg_param_ext_request_read.h \
    mavlink/common/mavlink_msg_param_ext_request_read.hpp \
    mavlink/common/mavlink_msg_param_ext_set.h \
    mavlink/common/mavlink_msg_param_ext_set.hpp \
    mavlink/common/mavlink_msg_param_ext_value.h \
    mavlink/common/mavlink_msg_param_ext_value.hpp \
    mavlink/common/mavlink_msg_param_map_rc.h \
    mavlink/common/mavlink_msg_param_map_rc.hpp \
    mavlink/common/mavlink_msg_param_request_list.h \
    mavlink/common/mavlink_msg_param_request_list.hpp \
    mavlink/common/mavlink_msg_param_request_read.h \
    mavlink/common/mavlink_msg_param_request_read.hpp \
    mavlink/common/mavlink_msg_param_set.h \
    mavlink/common/mavlink_msg_param_set.hpp \
    mavlink/common/mavlink_msg_param_value.h \
    mavlink/common/mavlink_msg_param_value.hpp \
    mavlink/common/mavlink_msg_ping.h \
    mavlink/common/mavlink_msg_ping.hpp \
    mavlink/common/mavlink_msg_play_tune.h \
    mavlink/common/mavlink_msg_play_tune.hpp \
    mavlink/common/mavlink_msg_position_target_global_int.h \
    mavlink/common/mavlink_msg_position_target_global_int.hpp \
    mavlink/common/mavlink_msg_position_target_local_ned.h \
    mavlink/common/mavlink_msg_position_target_local_ned.hpp \
    mavlink/common/mavlink_msg_power_status.h \
    mavlink/common/mavlink_msg_power_status.hpp \
    mavlink/common/mavlink_msg_protocol_version.h \
    mavlink/common/mavlink_msg_protocol_version.hpp \
    mavlink/common/mavlink_msg_radio_status.h \
    mavlink/common/mavlink_msg_radio_status.hpp \
    mavlink/common/mavlink_msg_raw_imu.h \
    mavlink/common/mavlink_msg_raw_imu.hpp \
    mavlink/common/mavlink_msg_raw_pressure.h \
    mavlink/common/mavlink_msg_raw_pressure.hpp \
    mavlink/common/mavlink_msg_rc_channels.h \
    mavlink/common/mavlink_msg_rc_channels.hpp \
    mavlink/common/mavlink_msg_rc_channels_override.h \
    mavlink/common/mavlink_msg_rc_channels_override.hpp \
    mavlink/common/mavlink_msg_rc_channels_raw.h \
    mavlink/common/mavlink_msg_rc_channels_raw.hpp \
    mavlink/common/mavlink_msg_rc_channels_scaled.h \
    mavlink/common/mavlink_msg_rc_channels_scaled.hpp \
    mavlink/common/mavlink_msg_request_data_stream.h \
    mavlink/common/mavlink_msg_request_data_stream.hpp \
    mavlink/common/mavlink_msg_resource_request.h \
    mavlink/common/mavlink_msg_resource_request.hpp \
    mavlink/common/mavlink_msg_safety_allowed_area.h \
    mavlink/common/mavlink_msg_safety_allowed_area.hpp \
    mavlink/common/mavlink_msg_safety_set_allowed_area.h \
    mavlink/common/mavlink_msg_safety_set_allowed_area.hpp \
    mavlink/common/mavlink_msg_scaled_imu.h \
    mavlink/common/mavlink_msg_scaled_imu.hpp \
    mavlink/common/mavlink_msg_scaled_imu2.h \
    mavlink/common/mavlink_msg_scaled_imu2.hpp \
    mavlink/common/mavlink_msg_scaled_imu3.h \
    mavlink/common/mavlink_msg_scaled_imu3.hpp \
    mavlink/common/mavlink_msg_scaled_pressure.h \
    mavlink/common/mavlink_msg_scaled_pressure.hpp \
    mavlink/common/mavlink_msg_scaled_pressure2.h \
    mavlink/common/mavlink_msg_scaled_pressure2.hpp \
    mavlink/common/mavlink_msg_scaled_pressure3.h \
    mavlink/common/mavlink_msg_scaled_pressure3.hpp \
    mavlink/common/mavlink_msg_serial_control.h \
    mavlink/common/mavlink_msg_serial_control.hpp \
    mavlink/common/mavlink_msg_servo_output_raw.h \
    mavlink/common/mavlink_msg_servo_output_raw.hpp \
    mavlink/common/mavlink_msg_set_actuator_control_target.h \
    mavlink/common/mavlink_msg_set_actuator_control_target.hpp \
    mavlink/common/mavlink_msg_set_attitude_target.h \
    mavlink/common/mavlink_msg_set_attitude_target.hpp \
    mavlink/common/mavlink_msg_set_gps_global_origin.h \
    mavlink/common/mavlink_msg_set_gps_global_origin.hpp \
    mavlink/common/mavlink_msg_set_home_position.h \
    mavlink/common/mavlink_msg_set_home_position.hpp \
    mavlink/common/mavlink_msg_set_mode.h \
    mavlink/common/mavlink_msg_set_mode.hpp \
    mavlink/common/mavlink_msg_set_position_target_global_int.h \
    mavlink/common/mavlink_msg_set_position_target_global_int.hpp \
    mavlink/common/mavlink_msg_set_position_target_local_ned.h \
    mavlink/common/mavlink_msg_set_position_target_local_ned.hpp \
    mavlink/common/mavlink_msg_set_video_stream_settings.h \
    mavlink/common/mavlink_msg_set_video_stream_settings.hpp \
    mavlink/common/mavlink_msg_setup_signing.h \
    mavlink/common/mavlink_msg_setup_signing.hpp \
    mavlink/common/mavlink_msg_sim_state.h \
    mavlink/common/mavlink_msg_sim_state.hpp \
    mavlink/common/mavlink_msg_statustext.h \
    mavlink/common/mavlink_msg_statustext.hpp \
    mavlink/common/mavlink_msg_storage_information.h \
    mavlink/common/mavlink_msg_storage_information.hpp \
    mavlink/common/mavlink_msg_sys_status.h \
    mavlink/common/mavlink_msg_sys_status.hpp \
    mavlink/common/mavlink_msg_system_time.h \
    mavlink/common/mavlink_msg_system_time.hpp \
    mavlink/common/mavlink_msg_terrain_check.h \
    mavlink/common/mavlink_msg_terrain_check.hpp \
    mavlink/common/mavlink_msg_terrain_data.h \
    mavlink/common/mavlink_msg_terrain_data.hpp \
    mavlink/common/mavlink_msg_terrain_report.h \
    mavlink/common/mavlink_msg_terrain_report.hpp \
    mavlink/common/mavlink_msg_terrain_request.h \
    mavlink/common/mavlink_msg_terrain_request.hpp \
    mavlink/common/mavlink_msg_timesync.h \
    mavlink/common/mavlink_msg_timesync.hpp \
    mavlink/common/mavlink_msg_uavcan_node_info.h \
    mavlink/common/mavlink_msg_uavcan_node_info.hpp \
    mavlink/common/mavlink_msg_uavcan_node_status.h \
    mavlink/common/mavlink_msg_uavcan_node_status.hpp \
    mavlink/common/mavlink_msg_v2_extension.h \
    mavlink/common/mavlink_msg_v2_extension.hpp \
    mavlink/common/mavlink_msg_vfr_hud.h \
    mavlink/common/mavlink_msg_vfr_hud.hpp \
    mavlink/common/mavlink_msg_vibration.h \
    mavlink/common/mavlink_msg_vibration.hpp \
    mavlink/common/mavlink_msg_vicon_position_estimate.h \
    mavlink/common/mavlink_msg_vicon_position_estimate.hpp \
    mavlink/common/mavlink_msg_video_stream_information.h \
    mavlink/common/mavlink_msg_video_stream_information.hpp \
    mavlink/common/mavlink_msg_vision_position_estimate.h \
    mavlink/common/mavlink_msg_vision_position_estimate.hpp \
    mavlink/common/mavlink_msg_vision_speed_estimate.h \
    mavlink/common/mavlink_msg_vision_speed_estimate.hpp \
    mavlink/common/mavlink_msg_wifi_config_ap.h \
    mavlink/common/mavlink_msg_wifi_config_ap.hpp \
    mavlink/common/mavlink_msg_wind_cov.h \
    mavlink/common/mavlink_msg_wind_cov.hpp \
    mavlink/common/testsuite.h \
    mavlink/common/version.h \
    mavlink/checksum.h \
    mavlink/mavlink_conversions.h \
    mavlink/mavlink_get_info.h \
    mavlink/mavlink_helpers.h \
    mavlink/mavlink_sha256.h \
    mavlink/mavlink_types.h \
    mavlink/message.hpp \
    mavlink/msgmap.hpp \
    mavlink/protocol.h \
    stream.h \
    serial.h

target.path = /home/pi
INSTALLS += target
